# Generated by Django 4.2 on 2023-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleNumber', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('vehicleType', models.IntegerField(default=2)),
                ('vehicleModel', models.CharField(default='', max_length=25)),
                ('vehicleDescription', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
