# Generated by Django 4.2 on 2023-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.IntegerField(choices=[(2, 'Two wheeler'), (3, 'Three wheeler'), (4, 'Four wheeler')], default=2),
        ),
    ]
